# source https://rhonabwy.com/2020/05/09/continuous-integration-with-github-actions-for-macos-and-ios-projects/

name: Swift

# uncomment to enable
#on:
#  push:
#    branches: [ main ]

jobs:
  build:
    
    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - { scheme: 'Release - ControlRoom', destination: 'platform=macOS' }

    steps:

    - name: Cancel redundant jobs
      uses: technote-space/auto-cancel-redundant-job@v1

    - name: Checkout Project
      uses: actions/checkout@v2

    #- name: Homebrew build helpers install
    #  run: brew bundle

    - name: Select Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12_beta.app

    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p

    - name: Show Build Settings
      run: xcodebuild -project ControlRoom.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' -showBuildSettings

    - name: Show Build SDK
      run: xcodebuild -project ControlRoom.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' -showsdks

    - name: Show Available Destinations
      run: xcodebuild -project ControlRoom.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' -showdestinations

    #- name: lint
    #  run: swift format lint --configuration .swift-format-config -r .

    - name: build and test
      run: xcodebuild clean build -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary
